# Site settings
title: Tristan is 8 - Birthday celebration
email: tristan@azeve.do
url: http://tristan.azeve.do
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Web Developer - Graphic Artist - User Experience Designer"
meta_author: Tristan Azevedo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Tristan Azevedo
  location: Location
  social: Maps
  credits: Phone

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: maps
    url: https://her.is/2FBzxWb


# Postal address (add as many lines as necessary)
address:
  - line: Straßburger Straße 9
  - line: 10405 Prenzlauer Berg

# Credits content
credits: '+49 152 5305 5016'

# Build settings
markdown: kramdown
permalink: pretty
